# On any tag push, we only need to build and deploy to PyPI.  Only existing
# commits can be tagged, so they must already have passed CI in the PR process.

trigger:
  tags:
    include: ["*"]

pr: none

jobs:
  - template: "jobs/wheels.yml"
    parameters:
      jobName: "linux"
      pool: Default
