---
name: Deploy release artifacts
on:
  push:
    tags:
      - '*'
jobs:
  build-core:
    name: Build core
    uses: ./.github/workflows/wheels-build.yml
    with:
      artifact-prefix: "deploy-core-"
      default-action: "skip"
      wheels-tier-1: "build"
      wheels-32bit: "build"
      sdist: "build"
  upload-core:
    name: Deploy core
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    needs: ["build-core"]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: 'deploy-core-*'
          merge-multiple: true
          path: deploy
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: deploy

  build-others:
    needs: ["upload-core"]
    name: Build others
    uses: ./.github/workflows/wheels-build.yml
    with:
      artifact-prefix: "deploy-others-"
      default-action: "build"
      wheels-tier-1: "skip"
      wheels-32bit: "skip"
      sdist: "skip"
  upload-others:
    name: Deploy other
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    needs: ["build-others"]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: 'deploy-others-*'
          merge-multiple: true
          path: deploy
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: deploy
