---
name: Deploy release artifacts
on:
  push:
    branches:
      - 'wheel-build-on-wheel-change-deploy'
jobs:
  build-core:
    name: Build core
    uses: ./.github/workflows/wheels-build.yml
    with:
      artifact-prefix: "deploy-core-"
      default-action: "skip"
      wheels-tier-1: "build"
      sdist: "build"
  upload-core:
    name: Deploy core
    needs: ["build-core"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: 'deploy-core-*'
          merge-multiple: true
          path: deploy
      - run: 'ls -1 ./deploy'

  build-others:
    name: Build others
    needs: ["upload-core"]
    uses: ./.github/workflows/wheels-build.yml
    with:
      artifact-prefix: "deploy-others-"
      default-action: "build"
      wheels-tier-1: "skip"
      wheels-32bit: "skip"
      sdist: "skip"
  upload-others:
    name: Deploy other
    needs: ["build-others"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: 'deploy-others-*'
          merge-multiple: true
          path: deploy
      - run: 'ls -1 ./deploy'
