name: Test wheel builds

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      # Above are the defaults for the PR trigger, below are our insertions.
      # Trigger on 'labeled' so we catch the initial manual labelling event.
      - labeled

concurrency:
  cancel-in-progress: true

jobs:
  test-wheels:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci: test wheels') }}
    uses: './.github/workflows/wheels-build.yml'
    with:
      default-action: "build"

  show-labels:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.even.pull_request.labels.*.name }}"
